baseURL: http://example.org/
languageCode: en-us
title: Write the Things
theme: van
relativeURLs: true
enableGitInfo: true
enableEmoji: true
enableInlineShortcodes: true
taxonomies:
  tag: tags
  category: categories
  hobby: hobbies
params.meta:
  favicon: true
favicon: "/themes/van/static/favicon.ico"
publishDir: docs

params:
  # Specify which content directory to render for left nav menu
  # Page is resolved by .GetPage function: https://gohugo.io/functions/getpage/
  # Set to '*' to render all sections to menu
  bookSection: "*"

  # /static/logo.png then the path would be logo.png
  bookLogo: logo.png

  # Configure date format used on pages
  bookDateFormat: "January 1, 2001"